variable "project-name" {}
variable "my-vpc-1" {}
variable "my-vpc-2" {}
variable "my-vpc-3" {}
variable "my-vpc-4" {}
variable "my-subnet-1" {}
variable "my-subnet-2" {}
variable "my-subnet-3" {}
variable "my-subnet-4" {}
